# Generated by Django 4.0.4 on 2022-04-16 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Keystone',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='description')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Max',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Rune_One',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Rune_Three',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Rune_Two',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Shard_One',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Shard_Three',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_Shard_Two',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('keystone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.keystone')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.path')),
                ('slot_rune_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_one')),
                ('slot_rune_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_three')),
                ('slot_rune_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_two')),
                ('slot_shard_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_shard_one')),
                ('slot_shard_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_shard_three')),
                ('slot_shard_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.slot_shard_two')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('champions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.champion')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.difficulty')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.item')),
                ('runes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.rune')),
                ('skill_max', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.skill_max')),
            ],
        ),
    ]
