# Generated by Django 4.0.4 on 2022-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystone',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
