# Generated by Django 4.0.4 on 2022-04-16 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='items',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='runes',
        ),
        migrations.AddField(
            model_name='matchup',
            name='rune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.keystone'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='slot_rune_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_one'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='slot_rune_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_three'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='slot_rune_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.slot_rune_two'),
        ),
    ]
