# Generated by Django 4.0.4 on 2022-04-16 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_items_matchup_item_remove_matchup_runes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative_Keystone',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='alternative_keystone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.alternative_keystone'),
        ),
    ]
