# Generated by Django 4.0.4 on 2022-05-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_keystone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
