# Generated by Django 4.0.4 on 2022-04-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alternative_keystone_matchup_alternative_keystone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative_keystone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alternative_keystone',
            name='name',
        ),
        migrations.AddField(
            model_name='alternative_keystone',
            name='alternative_keystone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.keystone'),
        ),
    ]
