# Generated by Django 4.0.4 on 2022-05-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_keystone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_rune_one',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot_rune_three',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot_rune_two',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot_shard_one',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot_shard_three',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot_shard_two',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
