# Generated by Django 4.0.4 on 2022-04-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_alternative_keystone_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative_keystone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
